apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "alertmanager.fullname" . }}-config
  namespace: observability
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m

    route:
      receiver: 'discord-notifications'
      group_by: ['alertname', 'severity']
      group_wait: 60s
      group_interval: 30m
      repeat_interval: 12h
      routes:
        - matchers:
            - severity="critical"
          receiver: 'discord-notifications'
          group_wait: 15s
          group_interval: 10m
          repeat_interval: 2h
        - matchers:
            - severity="warning"
          receiver: 'discord-notifications'
          group_wait: 60s
          group_interval: 30m
          repeat_interval: 12h

    receivers:
      - name: 'discord-notifications'
        discord_configs:
          - webhook_url_file: '/etc/alertmanager/discord_webhook_url'
            send_resolved: true

    inhibit_rules:
      - source_match:
          severity: 'critical'
        target_match:
          severity: 'warning'
        equal: ['alertname']
