apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-discord
  namespace: observability
type: Opaque
stringData:
  discord_webhook_url: "https://discord.com/api/webhooks/1480939424752603298/DISCORD_WEBHOOK_TOKEN_REDACTED"
