apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "paperless.fullname" . }}-data
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.paperless.persistence.data.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.paperless.persistence.data.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "paperless.fullname" . }}-media
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.paperless.persistence.media.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.paperless.persistence.media.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "paperless.fullname" . }}-consume
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.paperless.persistence.consume.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.paperless.persistence.consume.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "paperless.fullname" . }}-export
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.paperless.persistence.export.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.paperless.persistence.export.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "paperless.postgresql.fullname" . }}-data
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.postgresql.persistence.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.postgresql.persistence.size }}
