apiVersion: v1
kind: Secret
metadata:
  name: paperless-secrets
  namespace: apps
type: Opaque
stringData:
  PAPERLESS_SECRET_KEY: "PLACEHOLDER_ROTATE_ME"
  PAPERLESS_DBPASS: "PLACEHOLDER_ROTATE_ME"
  PAPERLESS_ADMIN_PASSWORD: "PLACEHOLDER_ROTATE_ME"
  POSTGRES_PASSWORD: "PLACEHOLDER_ROTATE_ME"
