image:
  repository: pihole/pihole
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: traefik
  host: pihole.k3s.local

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

persistence:
  enabled: true
  storageClassName: local-path
  size: 2Gi

env:
  TZ: "Europe/Lisbon"
  PIHOLE_DNS_: "8.8.8.8;1.1.1.1"
  VIRTUAL_HOST: "pihole.k3s.local"
  VIRTUAL_PORT: "80"
  # WEBPASSWORD stored in secret pihole-auth
