apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "jellyfin.fullname" . }}-config
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistence.config.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.persistence.config.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "jellyfin.fullname" . }}-cache
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistence.cache.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.persistence.cache.size }}
