apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pihole.fullname" . }}
  namespace: apps
  labels:
    app.kubernetes.io/name: {{ include "pihole.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "pihole.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "pihole.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: pihole
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
            - name: dns-tcp
              containerPort: 53
              protocol: TCP
            - name: dns-udp
              containerPort: 53
              protocol: UDP
          env:
            - name: TZ
              value: {{ .Values.env.TZ | quote }}
            - name: PIHOLE_DNS_
              value: {{ index .Values.env "PIHOLE_DNS_" | quote }}
            - name: VIRTUAL_HOST
              value: {{ .Values.env.VIRTUAL_HOST | quote }}
            - name: VIRTUAL_PORT
              value: {{ .Values.env.VIRTUAL_PORT | quote }}
            - name: WEBPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pihole-auth
                  key: WEBPASSWORD
          resources:
{{ toYaml .Values.resources | indent 12 }}
          readinessProbe:
            httpGet:
              path: /admin/
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /admin/
              port: http
            initialDelaySeconds: 40
            periodSeconds: 20
          volumeMounts:
            - name: data
              mountPath: /etc/pihole
      volumes:
        - name: data
{{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "pihole.fullname" . }}-data
{{- else }}
          emptyDir: {}
{{- end }}
