apiVersion: v1
kind: Service
metadata:
  name: {{ include "pihole.fullname" . }}
  namespace: apps
  labels:
    app.kubernetes.io/name: {{ include "pihole.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "pihole.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
