apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "authentik.postgresql.fullname" . }}-data
  namespace: apps
  labels:
    app.kubernetes.io/name: authentik-postgresql
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.postgresql.pvc.storageClass }}
  resources:
    requests:
      storage: {{ .Values.postgresql.pvc.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "authentik.fullname" . }}-media
  namespace: apps
  labels:
    app.kubernetes.io/name: authentik
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.media.pvc.storageClass }}
  resources:
    requests:
      storage: {{ .Values.media.pvc.size }}
