apiVersion: v1
kind: Secret
metadata:
    name: homepage-env
    namespace: apps
type: Opaque
stringData:
    HOMEPAGE_VAR_EXAMPLE: ENC[AES256_GCM,data:G0X9apVApsX12w==,iv:NtEe75baATpQNP53V5f/IKZO4z/jzDFJ9goGGK2gndQ=,tag:XsvA0jSEP9welkQc34eRmA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18qmemsqgr3gpcmmhjwjmhpp8tqd2ae5s0g5x0u4qwuu94nx3fuls8t5fc8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpaEZSRndQMVpKdlV0Qytw
            UDJPeFVPSFYvYjQ2SHBqdVF4enEzWHlDMUJFCnIwbGVPUGE5ek9odGwwODg1bDZj
            ZWpGUUFBODZDMGlHelFnNUdyb3FZTWcKLS0tIGw3WlNacUprdWZqU1JJNmo3Nm9S
            d3owbis1Q3pURWd5UG5leWFKVkpVQzQKV7quBUh2VgPQLWjwljshks6nFTSMKndC
            zfnGuNLxiSmsSCVPp0GGQdJl57NoNlM25Lz98scOVT0NH802ay9ocw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T18:44:38Z"
    mac: ENC[AES256_GCM,data:W5PnanLh7KLI6D6C21kqx0giLlJwFN89nAg0mB4npzbQbNgmpSavPTdfkMwoe2/+ZXM6XneBSPoe8i8vnlMNl2gizFppZXHmdT9ZJ/dxC6SOiPWUzr41PAaBaMRCL7aw5uC5/RA8FNQGyF7l9InnBqyEUF9JxlYo6SsIFQg2xAQ=,iv:pTl2pl5Qfm35d5S8J9PjmK+PSvv12HDYzAWlUKcJkvE=,tag:8N73GHWOWYsGyD8nywV3Vg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
