nextcloud:
  image:
    repository: nextcloud
    tag: "latest"
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: true
    className: traefik
    host: nextcloud.k3s.local

  resources:
    requests:
      cpu: 300m
      memory: 512Mi
    limits:
      cpu: 2000m
      memory: 2Gi

  persistence:
    html:
      storageClassName: local-path
      size: 10Gi
    data:
      storageClassName: local-path
      size: 5Gi

  env:
    NEXTCLOUD_TRUSTED_DOMAINS: "cloud.luk-homeserver.com.br 100.95.204.103"
    MYSQL_DATABASE: "nextcloud"
    MYSQL_USER: "nextcloud"
    MYSQL_HOST: "nextcloud-mariadb"
    REDIS_HOST: "nextcloud-redis"
    OVERWRITEPROTOCOL: "https"
    OVERWRITEHOST: "cloud.luk-homeserver.com.br"
    TZ: "America/Sao_Paulo"
    TRUSTED_PROXIES: "100.95.204.103"
    PHP_MEMORY_LIMIT: "512M"
    PHP_UPLOAD_LIMIT: "512M"

mariadb:
  image:
    repository: mariadb
    tag: "latest"
    pullPolicy: IfNotPresent

  service:
    port: 3306

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1Gi

  persistence:
    storageClassName: local-path
    size: 5Gi

  env:
    MYSQL_DATABASE: "nextcloud"
    MYSQL_USER: "nextcloud"

redis:
  image:
    repository: redis
    tag: "alpine"
    pullPolicy: IfNotPresent

  service:
    port: 6379

  resources:
    requests:
      cpu: 50m
      memory: 32Mi
    limits:
      cpu: 200m
      memory: 128Mi
