---
- Repos:
    - GitHub:
        - abbr: GH
          href: https://github.com/LucasSantana-Dev
    - Lucky:
        - abbr: LK
          href: https://github.com/LucasSantana-Dev/Lucky
    - Homelab:
        - abbr: HL
          href: https://github.com/LucasSantana-Dev/homelab

- Cloud:
    - Cloudflare:
        - abbr: CF
          href: https://dash.cloudflare.com
    - Tailscale:
        - abbr: TS
          href: https://login.tailscale.com/admin/machines

- Workspace:
    - Gmail:
        - abbr: GM
          href: https://mail.google.com
    - Calendar:
        - abbr: CA
          href: https://calendar.google.com
    - Drive:
        - abbr: DR
          href: https://drive.google.com
