title: Luk's Homelab
description: Ultra-Modern Homelab Dashboard
logo: https://cdn0.iconfinder.com/data/icons/famous-character-vol-1-colored/48/JD-37-512.png
favicon: https://cdn0.iconfinder.com/data/icons/famous-character-vol-1-colored/48/JD-37-512.png
background:
  image: https://vsthemes.org/uploads/posts/2021-01/1610083382_skrinshot-08-01-2021-10_20_29.webp
  blur: sm
theme: dark
color: indigo
headerStyle: clean
hideVersion: true
target: _self
hideErrors: false
showStats: true
statusStyle: dot
language: en
cardBlur: xs
iconStyle: theme