title: Luk's Homelab
description: Self-hosted dashboard
favicon: /icons/yoda.png
theme: dark
color: slate
headerStyle: boxedWidgets
target: _self
hideVersion: true
hideErrors: false
showStats: true
statusStyle: dot
language: en
iconStyle: theme
background:
  blur: xl
  saturate: 50
  brightness: 50
  opacity: 100
cardBlur: md
pages:
- name: Home
  icon: mdi-home
- name: Projects
  icon: mdi-source-repository
layout:
  Media:
    style: row
    columns: 4
  Storage:
    style: row
    columns: 4
  Home:
    style: row
    columns: 4
  Apps:
    style: row
    columns: 4
  Management:
    style: row
    columns: 6
  Backup:
    style: row
    columns: 4
  Infrastructure:
    style: row
    columns: 6
  maxGroupColumns: 6
  useEqualHeights: true
