apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "uptime-kuma.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "uptime-kuma.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "uptime-kuma.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "uptime-kuma.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: uptime-kuma
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3001
          resources:
{{ toYaml .Values.resources | indent 12 }}
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
          volumeMounts:
            - name: data
              mountPath: /app/data
      volumes:
        - name: data
{{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "uptime-kuma.fullname" . }}-data
{{- else }}
          emptyDir: {}
{{- end }}
