image:
  repository: ghcr.io/home-assistant/home-assistant
  tag: "stable"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8123

ingress:
  enabled: true
  className: traefik
  host: homeassistant.k3s.local

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi

persistence:
  enabled: true
  storageClassName: local-path
  size: 5Gi

env:
  TZ: "America/Sao_Paulo"
