image:
  repository: quay.io/prometheus/blackbox-exporter
  tag: v0.25.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9115

ingress:
  enabled: true
  className: traefik
  host: blackbox.k3s.local
  tlsSecretName: ""

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

config:
  modules:
    http_2xx:
      prober: http
      timeout: 5s
      http:
        preferred_ip_protocol: ip4
