apiVersion: v1
kind: ResourceQuota
metadata:
  name: observability-budget
  namespace: observability
spec:
  hard:
    requests.cpu: "500m"
    requests.memory: 1024Mi
    limits.cpu: "1000m"
    limits.memory: 1536Mi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: apps-budget
  namespace: apps
spec:
  hard:
    requests.cpu: "1000m"
    requests.memory: 2048Mi
    limits.cpu: "1500m"
    limits.memory: 3072Mi
