image:
  repository: vaultwarden/server
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  websocketPort: 3012

ingress:
  enabled: true
  className: traefik
  host: vault.k3s.local

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 512Mi

persistence:
  enabled: true
  storageClassName: local-path
  size: 5Gi

env:
  WEBSOCKET_ENABLED: "true"
  SIGNUPS_ALLOWED: "false"
  DOMAIN: "https://vault.luk-homeserver.com.br"

envFromSecret: ""
