#!/bin/bash
# Guide for setting up DNS on client devices

set -euo pipefail

TAILSCALE_IP=$(grep TAILSCALE_IP .env 2>/dev/null | cut -d'=' -f2 || echo "100.64.0.10")

echo "📋 DNS Setup Guide for Client Devices"
echo "====================================="
echo ""
echo "Your device needs DNS configuration to resolve ${DOMAIN}"
echo "Current Tailscale IP: $TAILSCALE_IP"
echo ""
echo "🔧 Option 1: Tailscale MagicDNS (Recommended - Works on all devices)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Go to: https://login.tailscale.com/admin/dns"
echo ""
echo "2. Click 'Add nameserver' and add:"
echo "   Type: Custom"
echo "   Address: 100.100.100.100"
echo ""
echo "3. Click 'Add DNS record' and add:"
echo "   Domain: ${DOMAIN}"
echo "   Type: A"
echo "   Value: $TAILSCALE_IP"
echo ""
echo "4. Add wildcard record:"
echo "   Domain: *.${DOMAIN}"
echo "   Type: A"
echo "   Value: $TAILSCALE_IP"
echo ""
echo "5. Enable MagicDNS for your tailnet"
echo ""
echo "6. On your device, ensure Tailscale is using MagicDNS:"
echo "   - Open Tailscale app"
echo "   - Go to Settings"
echo "   - Enable 'Use Tailscale DNS'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔧 Option 2: /etc/hosts File (Quick Fix - Desktop Only)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "On Linux/macOS (run with sudo):"
echo "  sudo nano /etc/hosts"
echo ""
echo "On Windows (Run as Administrator):"
printf '%s\n' '  notepad C:\Windows\System32\drivers\etc\hosts'
echo ""
echo "Add these lines:"
echo ""
echo "$TAILSCALE_IP ${DOMAIN} www.${DOMAIN}"
echo "$TAILSCALE_IP stremio.${DOMAIN}"
echo "$TAILSCALE_IP auth.${DOMAIN}"
echo "$TAILSCALE_IP jellyfin.${DOMAIN}"
echo "$TAILSCALE_IP grafana.${DOMAIN}"
echo "$TAILSCALE_IP portainer.${DOMAIN}"
echo "$TAILSCALE_IP homeassistant.${DOMAIN}"
echo "$TAILSCALE_IP vault.${DOMAIN}"
echo "$TAILSCALE_IP cloud.${DOMAIN}"
echo "$TAILSCALE_IP docs.${DOMAIN}"
echo "$TAILSCALE_IP n8n.${DOMAIN}"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔧 Option 3: Use Direct IP (No DNS Needed)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "For Stremio, use:"
echo "  http://$TAILSCALE_IP:11470"
echo ""
echo "Or for HTTPS services, you'll need DNS configured."
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ After configuring, test with:"
echo "   ping stremio.${DOMAIN}"
echo "   (Should resolve to $TAILSCALE_IP)"
echo ""
