#!/bin/bash
# Script to help diagnose device connectivity issues

set -euo pipefail

TAILSCALE_IP="100.64.0.10"
PORT="11470"

echo "🔍 Device Connectivity Diagnostic"
echo "=================================="
echo ""
echo "Run these commands ON YOUR DEVICE (not the server):"
echo ""
echo "1️⃣  Test Tailscale connectivity:"
echo "   ping $TAILSCALE_IP"
echo "   (Should get responses if Tailscale is working)"
echo ""
echo "2️⃣  Test port connectivity:"
echo "   telnet $TAILSCALE_IP $PORT"
echo "   (Or use: nc -zv $TAILSCALE_IP $PORT)"
echo "   (Should connect if port is accessible)"
echo ""
echo "3️⃣  Test HTTP connection:"
echo "   curl -v http://$TAILSCALE_IP:$PORT/"
echo "   (Should get HTTP 307 redirect)"
echo ""
echo "4️⃣  Check Tailscale status on your device:"
echo "   tailscale status"
echo "   (Should show homelab-node as online)"
echo ""
echo "5️⃣  Check if your device firewall is blocking:"
echo "   - Windows: Check Windows Firewall"
echo "   - macOS: Check System Preferences > Security > Firewall"
echo "   - Linux: Check iptables/ufw"
echo ""
echo "6️⃣  Test from browser:"
echo "   Open: http://$TAILSCALE_IP:$PORT"
echo "   (Should redirect to app.strem.io)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "💡 Common Issues:"
echo ""
echo "❌ 'Connection refused' or timeout:"
echo "   - Your device might not be on Tailscale network"
echo "   - Firewall blocking port $PORT"
echo "   - Tailscale not running on your device"
echo ""
echo "❌ 'Network unreachable':"
echo "   - Tailscale not connected"
echo "   - Wrong Tailscale IP"
echo ""
echo "❌ Stremio app shows 'Error':"
echo "   - App might need network permissions"
echo "   - Try clearing app cache"
echo "   - Try updating Stremio app"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ Server Status (from server):"
echo "   - Port $PORT is listening on $TAILSCALE_IP"
echo "   - Stremio server is running"
echo "   - Service is responding"
echo ""
echo "The server is ready. The issue is on the client side."
echo ""
