apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "n8n.fullname" . }}
  namespace: apps
  labels:
    app.kubernetes.io/name: {{ include "n8n.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "n8n.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
