apiVersion: v1
kind: Secret
metadata:
  name: n8n-auth
  namespace: apps
  labels:
    app.kubernetes.io/name: {{ include "n8n.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  N8N_BASIC_AUTH_USER: {{ .Values.auth.user | quote }}
  N8N_BASIC_AUTH_PASSWORD: {{ required "auth.password is required" .Values.auth.password | quote }}
