{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "filebrowser.fullname" . }}-db
  labels:
    app.kubernetes.io/name: {{ include "filebrowser.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.dbSize }}
  storageClassName: {{ .Values.persistence.storageClassName }}
{{- end }}
