image:
  repository: grafana/loki
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3100

ingress:
  enabled: false

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

persistence:
  enabled: true
  storageClassName: local-path
  size: 10Gi
